export const mockData = ({
	"concatenatedAddress": "Zetlitz` gate 4, 5006 BERGEN",
	"ownershipType": "Selveier",
	"livingArea": 38,
	"commonDebt": null,
	"price": 2500000,
	"floor": 1,
	"numberOfFloors": 3,
	"numberOfBedrooms": 1,
	"estateType": "Leilighet",
	"buildYear": 1890,
	"previousSalesDate": null,
	"squareMeterPrice": "65 789",
	"latitude": "60.3843128525617",
	"longitude": "5.3235969390769",
	"priceAssumption": null,
	"transactionTime": null,
	"estateId": 1562758,
	"saleId": 186872439,
	"housingCooperativeShareSaleId": 0,
	"housingCooperativeShareId": null,
	"lookupSaleId": 186872439,
	"estateTypeEnum": 4,
	"lat": 60.38431285256175,
	"lng": 5.323596939076904,
	"ownershipTypeEnum": 2,
	"rooms": 0,
	"isNearbySale": false,
	"isComparable": false,
	"isOnStreet": false,
	"isInBuilding": false,
	"isSearch": false,
	"isChecked": false,
	"internalId": 0,
	"distanceToTarget": 0,
	"presentationImageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058607&thumbnail=True",
	"usageArea": 38,
	"grossArea": 44,
	"isAppartement": true,
	"siteArea": 188.4,
	"siteType": "Selveier",
	"organizationNumber": null,
	"priceIncludingCommonDebt": 0,
	"hasSale": true,
	"calculatedSquareMeterPrice": 65789.47368421052,
	"hasCurrentCommonDebt": false,
	"currentCommonDebt": null,
	"facilities": null,
	"saleHistory": {
		"containsUncertainPrice": true,
		"containsProspect": true,
		"containsImages": true,
		"saleHistoryList": [{
			"registeredDate": "01.12.2017",
			"soldDate": new Date("2019-01-10T08:27:24.562Z"),
			"publicRegistrationDate": "01.12.2017",
			"priceAssumption": null,
			"salesPrice": 2500000,
			"surveyorsValuation": null,
			"commonDebt": null,
			"squareMeterPrice": 65789.47368421052,
			"estateAgent": null,
			"transactionTime": null,
			"indexPrice": null,
			"isUncertainPrice": false,
			"uncertainPriceReason": "",
			"images": [],
			"sortableDate": new Date("2017-12-01T21:00:00"),
			"sortableDateText": "01.12.2017",
			"saleComment": "",
			"hasImages": false,
			"noImages": true,
			"hasProspect": false,
			"numberOfImages": 0,
			"index": 0,
			"saleStatus": 0,
			"withdrawnDate": null,
			"withdrawnAfterDays": null,
			"layTime": 398,
			"isPublicRegDateOnly": true,
			"totalPrice": 2500000,
			"totalPriceAssumption": 0,
			"saleInfoText": "Tinglyst 01.12.2017 ",
			"saleId": 186872439,
			"numberOfPriceAssumptions": null,
			"priceAssumptionHistory": null,
			"selectedForIndexedValuation": false,
			"expanded": false,
			"showInfoRowToolTip": false,
			"showPriceAssumptionsToolTip": false,
			"assumptions": [],
			"showUncertainPriceTooTip": false,
			"estateType": "Leilighet",
			"hidden": false
		}, {
			"registeredDate": "11.02.2016",
			"soldDate": "17.02.2016",
			"publicRegistrationDate": "03.05.2016",
			"priceAssumption": 2190000,
			"salesPrice": 2480000,
			"surveyorsValuation": 2200000,
			"commonDebt": null,
			"squareMeterPrice": 65263.15789473684,
			"estateAgent": "Fana Sparebank Eiendom",
			"transactionTime": 6,
			"indexPrice": null,
			"isUncertainPrice": false,
			"uncertainPriceReason": "",
			"images": [{
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058607&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058607&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058608&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058608&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058617&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058617&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058618&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058618&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058619&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058619&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058620&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058620&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058621&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058621&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058622&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058622&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058623&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058623&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058624&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058624&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058625&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058625&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058626&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058626&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058609&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058609&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058627&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058627&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058628&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058628&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058629&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058629&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058630&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058630&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058631&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058631&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058632&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058632&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058633&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058633&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058634&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058634&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058635&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058635&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058636&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058636&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058610&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058610&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058637&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058637&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058638&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058638&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058639&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058639&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058640&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058640&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058641&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058641&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058642&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058642&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058643&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058643&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058644&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058644&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058611&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058611&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058612&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058612&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058613&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058613&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058614&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058614&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058615&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058615&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058616&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=19058616&thumbnail=True",
				"smallThumbnailUrl": null
			}
			],
			"sortableDate": new Date("2016-02-17T00:00:00"),
			"sortableDateText": "17.02.2016",
			"saleComment": "",
			"hasImages": true,
			"noImages": false,
			"hasProspect": true,
			"numberOfImages": 38,
			"index": 0,
			"saleStatus": 0,
			"withdrawnDate": new Date("2016-02-22T07:07:18.943"),
			"withdrawnAfterDays": 11,
			"layTime": 1058,
			"isPublicRegDateOnly": false,
			"totalPrice": 2480000,
			"totalPriceAssumption": 2190000,
			"saleInfoText": "Solgt 17.02.2016 ",
			"saleId": 186872432,
			"numberOfPriceAssumptions": null,
			"priceAssumptionHistory": null,
			"selectedForIndexedValuation": false,
			"expanded": false,
			"showInfoRowToolTip": false,
			"showPriceAssumptionsToolTip": false,
			"assumptions": [],
			"showUncertainPriceTooTip": false,
			"estateType": "Leilighet",
			"hidden": false
		}, {
			"registeredDate": "25.05.2012",
			"soldDate": "",
			"publicRegistrationDate": "04.07.2012",
			"priceAssumption": 1860000,
			"salesPrice": 1860000,
			"surveyorsValuation": 1900000,
			"commonDebt": null,
			"squareMeterPrice": 48947.36842105263,
			"estateAgent": "Kaland & Partners - Torgallmenningen Eiendomsmegling",
			"transactionTime": null,
			"indexPrice": null,
			"isUncertainPrice": false,
			"uncertainPriceReason": "",
			"images": [{
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525673&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525673&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525674&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525674&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525683&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525683&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525684&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525684&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525685&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525685&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525686&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525686&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525687&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525687&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525688&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525688&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525689&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525689&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525675&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525675&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525676&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525676&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525677&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525677&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525678&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525678&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525679&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525679&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525680&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525680&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525681&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525681&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525682&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=9525682&thumbnail=True",
				"smallThumbnailUrl": null
			}
			],
			"sortableDate": new Date("2012-07-04T00:00:00"),
			"sortableDateText": "04.07.2012",
			"saleComment": "",
			"hasImages": true,
			"noImages": false,
			"hasProspect": true,
			"numberOfImages": 17,
			"index": 0,
			"saleStatus": 0,
			"withdrawnDate": new Date("2012-06-01T15:35:28.807"),
			"withdrawnAfterDays": 7,
			"layTime": 2415,
			"isPublicRegDateOnly": true,
			"totalPrice": 1860000,
			"totalPriceAssumption": 1860000,
			"saleInfoText": "Tinglyst 04.07.2012 ",
			"saleId": 186872433,
			"numberOfPriceAssumptions": null,
			"priceAssumptionHistory": null,
			"selectedForIndexedValuation": false,
			"expanded": false,
			"showInfoRowToolTip": false,
			"showPriceAssumptionsToolTip": false,
			"assumptions": [],
			"showUncertainPriceTooTip": false,
			"estateType": "Leilighet",
			"hidden": false
		}, {
			"registeredDate": "31.01.2008",
			"soldDate": "26.02.2008",
			"publicRegistrationDate": "10.03.2008",
			"priceAssumption": 1590000,
			"salesPrice": 1600000,
			"surveyorsValuation": 1650000,
			"commonDebt": null,
			"squareMeterPrice": 42105.26315789474,
			"estateAgent": "DnB NOR Eiendom",
			"transactionTime": 26,
			"indexPrice": null,
			"isUncertainPrice": false,
			"uncertainPriceReason": "",
			"images": [{
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193287&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193287&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193288&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193288&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193297&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193297&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193289&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193289&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193290&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193290&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193291&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193291&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193292&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193292&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193293&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193293&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193294&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193294&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193295&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193295&thumbnail=True",
				"smallThumbnailUrl": null
			}, {
				"imageUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193296&thumbnail=False",
				"largeThumbnailUrl": "/ManualValuation/Resource/SaleImage?saleImageId=1193296&thumbnail=True",
				"smallThumbnailUrl": null
			}
			],
			"sortableDate": new Date("2008-02-26T00:00:00"),
			"sortableDateText": "26.02.2008",
			"saleComment": "",
			"hasImages": true,
			"noImages": false,
			"hasProspect": true,
			"numberOfImages": 11,
			"index": 0,
			"saleStatus": 0,
			"withdrawnDate": null,
			"withdrawnAfterDays": null,
			"layTime": 3991,
			"isPublicRegDateOnly": false,
			"totalPrice": 1600000,
			"totalPriceAssumption": 1590000,
			"saleInfoText": "Solgt 26.02.2008 ",
			"saleId": 186872434,
			"numberOfPriceAssumptions": null,
			"priceAssumptionHistory": null,
			"selectedForIndexedValuation": false,
			"expanded": false,
			"showInfoRowToolTip": false,
			"showPriceAssumptionsToolTip": false,
			"assumptions": [],
			"showUncertainPriceTooTip": false,
			"estateType": "Leilighet",
			"hidden": false
		}, {
			"registeredDate": "16.03.2007",
			"soldDate": "",
			"publicRegistrationDate": "",
			"priceAssumption": 1690000,
			"salesPrice": null,
			"surveyorsValuation": 1820000,
			"commonDebt": null,
			"squareMeterPrice": 44473.68421052631,
			"estateAgent": "Eiendomsmegler Vest",
			"transactionTime": null,
			"indexPrice": null,
			"isUncertainPrice": true,
			"uncertainPriceReason": "Eiendommer har ligget i markedet i mer enn 180 dager uten registrert salgspris og prisantydning bør derfor behandles som usikker",
			"images": [],
			"sortableDate": "2007-03-16T00:00:00",
			"sortableDateText": "16.03.2007",
			"saleComment": "Eiendommer har ligget i markedet i mer enn 180 dager uten registrert salgspris og prisantydning bør derfor behandles som usikker",
			"hasImages": false,
			"noImages": true,
			"hasProspect": true,
			"numberOfImages": 0,
			"index": 0,
			"saleStatus": 1,
			"withdrawnDate": null,
			"withdrawnAfterDays": null,
			"layTime": 4312,
			"isPublicRegDateOnly": false,
			"totalPrice": 0,
			"totalPriceAssumption": 1690000,
			"saleInfoText": "Til salgs fra 16.03.2007 ",
			"saleId": 186872435,
			"numberOfPriceAssumptions": null,
			"priceAssumptionHistory": null,
			"selectedForIndexedValuation": false,
			"expanded": false,
			"showInfoRowToolTip": false,
			"showPriceAssumptionsToolTip": false,
			"assumptions": [],
			"showUncertainPriceTooTip": false,
			"estateType": "Leilighet",
			"hidden": false
		}, {
			"registeredDate": "13.06.2002",
			"soldDate": "26.07.2002",
			"publicRegistrationDate": "21.08.2002",
			"priceAssumption": 890000,
			"salesPrice": 960000,
			"surveyorsValuation": 910000,
			"commonDebt": null,
			"squareMeterPrice": 25263.157894736843,
			"estateAgent": "DnB Eiendomsmegling AS Bergen Sentrum",
			"transactionTime": 43,
			"indexPrice": null,
			"isUncertainPrice": false,
			"uncertainPriceReason": "",
			"images": [],
			"sortableDate": new Date("2002-07-26T00:00:00"),
			"sortableDateText": "26.07.2002",
			"saleComment": "",
			"hasImages": false,
			"noImages": true,
			"hasProspect": false,
			"numberOfImages": 0,
			"index": 0,
			"saleStatus": 0,
			"withdrawnDate": null,
			"withdrawnAfterDays": null,
			"layTime": 6049,
			"isPublicRegDateOnly": false,
			"totalPrice": 960000,
			"totalPriceAssumption": 890000,
			"saleInfoText": "Solgt 26.07.2002 ",
			"saleId": 186872436,
			"numberOfPriceAssumptions": null,
			"priceAssumptionHistory": null,
			"selectedForIndexedValuation": false,
			"expanded": false,
			"showInfoRowToolTip": false,
			"showPriceAssumptionsToolTip": false,
			"assumptions": [],
			"showUncertainPriceTooTip": false,
			"estateType": "Leilighet",
			"hidden": false
		}, {
			"registeredDate": "12.04.1991",
			"soldDate": "",
			"publicRegistrationDate": "12.04.1991",
			"priceAssumption": null,
			"salesPrice": 443000,
			"surveyorsValuation": null,
			"commonDebt": null,
			"squareMeterPrice": 11657.894736842105,
			"estateAgent": null,
			"transactionTime": null,
			"indexPrice": null,
			"isUncertainPrice": false,
			"uncertainPriceReason": "",
			"images": [],
			"sortableDate": new Date("1991-04-12T00:00:00"),
			"sortableDateText": "12.04.1991",
			"saleComment": "",
			"hasImages": false,
			"noImages": true,
			"hasProspect": false,
			"numberOfImages": 0,
			"index": 0,
			"saleStatus": 0,
			"withdrawnDate": null,
			"withdrawnAfterDays": null,
			"layTime": 10129,
			"isPublicRegDateOnly": true,
			"totalPrice": 443000,
			"totalPriceAssumption": 0,
			"saleInfoText": "Tinglyst 12.04.1991 ",
			"saleId": 186872438,
			"numberOfPriceAssumptions": null,
			"priceAssumptionHistory": null,
			"selectedForIndexedValuation": false,
			"expanded": false,
			"showInfoRowToolTip": false,
			"showPriceAssumptionsToolTip": false,
			"assumptions": [],
			"showUncertainPriceTooTip": false,
			"estateType": "Leilighet",
			"hidden": true
		}, {
			"registeredDate": "06.02.1990",
			"soldDate": "",
			"publicRegistrationDate": "06.02.1990",
			"priceAssumption": null,
			"salesPrice": 820000,
			"surveyorsValuation": null,
			"commonDebt": null,
			"squareMeterPrice": 21578.947368421053,
			"estateAgent": null,
			"transactionTime": null,
			"indexPrice": null,
			"isUncertainPrice": true,
			"uncertainPriceReason": "Omsetningen gjelder <n> eiendommer og bør ikke hensyntas som et reellt markedssalg",
			"images": [],
			"sortableDate": new Date("1990-02-06T00:00:00"),
			"sortableDateText": "06.02.1990",
			"saleComment": "Omsetningen gjelder 7 eiendommer og bør ikke hensyntas som et reelt markedssalg",
			"hasImages": false,
			"noImages": true,
			"hasProspect": false,
			"numberOfImages": 0,
			"index": 0,
			"saleStatus": 0,
			"withdrawnDate": null,
			"withdrawnAfterDays": null,
			"layTime": 10559,
			"isPublicRegDateOnly": true,
			"totalPrice": 820000,
			"totalPriceAssumption": 0,
			"saleInfoText": "Tinglyst 06.02.1990 ",
			"saleId": 186872437,
			"numberOfPriceAssumptions": null,
			"priceAssumptionHistory": null,
			"selectedForIndexedValuation": false,
			"expanded": false,
			"showInfoRowToolTip": false,
			"showPriceAssumptionsToolTip": false,
			"assumptions": [],
			"showUncertainPriceTooTip": false,
			"estateType": "Leilighet",
			"hidden": true
		}
		]
	},
	"shareNumber": null,
	"addressId": 3457616,
	"cityDistrictId": 44,
	"municipalityId": 201,
	"customPrice": "2 500 000",
	"calculatedPrice": null,
	"calculatedTotal": 2547728.9365211143,
	"indexDeltaPercentage": 2,
	"calculatedArea": 38,
	"isCustom": false,
	"actualSaleDate": "",
	"saleDate": "",
	"saleDateTime": null,
	"sortDate": new Date("2017-12-01T21:00:00"),
	"numberOfSales": 8,
	"numberOfImages": 66,
	"numberOfFacilities": null,
	"estimateDate": new Date("2019-01-04T14:56:24.6193603+01:00"),
	"currentCommonDebtDate": null,
	"estateAgent": null,
	"concatenatedMatrikkel": "1201-164/411/0/1",
	"ownershipEstateTypeDisplayText": "Selveierleilighet",
	"estateAgentHeadOffice": "",
	"gNr": 164,
	"bNr": 411,
	"fNr": 0,
	"sNr": 1,
	"kNr": 1201,
	"downloadedVirtualProspectPath": null,
	"hasProspect": false,
	"priceAssumptionHistory": null,
	"numberOfPriceAssumptions": null,
	"municipalityNumber": 1201,
	"streetAddress": "Zetlitz` gate 4 ",
	"postalAddress": "5006 BERGEN",
	"isPublicRegDateOnly": false,
	"publicRegistrationDate": null,
	"estateSubType": "Leilighet (i blokk)",
	"estateSubTypeEnum": 404,
	"features": ["Innredet loft"],
	"featureEnums": [1],
	"energyLabel": "ukjent",
	"energyLabelingColorEnum": 5,
	"energyLabelingColor": "",
	"energyLabelClass": "ukjent-red",
	"isHousingCooperative": false,
	"identificationText": "1201-164/411/0/1",
	"hideEstateInfo": true,
	"hideManualValuation": false,
	"hideShowInmap": false,
	"appraisalUrl": "/ManualValuation/ExternalLinks/GetCreateAppraisalRedirect?estateId=1562758&addressId=3457616&organizationNumber=null&shareNumber=null"
});